version: '3.4'

services:
  hophubapi:
    image: ${DOCKER_REGISTRY-}hophubapi
    container_name: "hophubapi"
    build:
      context: .
      dockerfile: HopHubApi/Dockerfile
  postgres:
    image: "postgres:11"
    container_name: "hophubpostgres"
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'password'
    links:
      - hophubapi
    ports:
      - "54320:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: "hophubpgadmin"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
volumes:
  db_data:
  pgadmin: